INSERT INTO PUBLIC.CAKES (CATEGORY, INGREDIENTS, NAME, PRICE) VALUES ('CUPCAKES', 'milk,egg,salt', 'blueberry-cupcake', 100);
INSERT INTO PUBLIC.CAKES (CATEGORY, INGREDIENTS, NAME, PRICE) VALUES ('CHEESECAKES', 'egg,milk,salt', 'vanilla-cheesecake', 150);
