### Adding user as CLIENT
POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "firstName": "Jackie",
  "lastName": "Chan",
  "email": "example@mail.com",
  "password": "Qwerty123!",
  "town": "Hamburg",
  "zipCode": "44551",
  "street": "Norbert-Schmid-Platz",
  "houseNumber": "11",
  "phoneNumber": "+4917611223344"
}

### Adding user as CONFECTIONER
POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "firstName": "Will",
  "lastName": "Smith",
  "email": "simple@mail.com",
  "password": "willS007!",
  "town": "Kiel",
  "zipCode": "22312",
  "street": "StadtStrasse",
  "houseNumber": "49",
  "phoneNumber": "+4917699887766"
}

### Adding user as MANAGER
POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Manageroff",
  "email": "manager@mail.com",
  "password": "Manager007!",
  "town": "Kiel",
  "zipCode": "55212",
  "street": "StrandStrasse",
  "houseNumber": "21",
  "phoneNumber": "+4917688776655"
}
### Получение профиля пользователя

GET http://localhost:8080/api/users/my

### Getting all Users by Role
GET localhost:8080/api/users/role/CONFECTIONER
