### Adding user as CLIENT
POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "fullName": "Jackie Chan",
  "email": "example@mail.com",
  "password": "Qwerty123!",
  "town": "Hamburg",
  "street": "Norbert-Schmid-Platz",
  "houseNumber": "11",
  "phoneNumber": "+4917611223344"
}

### Adding user as CONFECTIONER
POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "fullName": "Will Smith",
  "email": "simple@mail.com",
  "password": "willS007!",
  "town": "Kiel",
  "street": "StadtStrasse",
  "houseNumber": "49",
  "phoneNumber": "+4917699887766"
}

### Adding user as MANAGER
POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "fullName": "Vasiliy Morozov",
  "email": "manager@mail.com",
  "password": "Manager007!",
  "town": "Kiel",
  "street": "StrandStrasse",
  "houseNumber": "21",
  "phoneNumber": "+4917688776655"
}
### Получение профиля пользователя

GET http://localhost:8080/api/users/my