### add cake MOUSSE
POST localhost:8080/api/cakes
Content-Type: application/json

{
  "name": "strawberry-mousse",
  "ingredients": "water, sugar, egg",
  "price": "250.00",
  "category": "MOUSSE",
  "state": "CREATED"
}

### add cake CUPCAKES
POST localhost:8080/api/cakes
Content-Type: application/json

{
  "name": "strawberry-mousse",
  "ingredients": "water, sugar, egg",
  "price": "250.00",
  "category": "CUPCAKES",
  "state": "CREATED"
}


### get all cakes
GET localhost:8080/api/cakes?page=1&orderBy=id&desc=false


### get cake
GET localhost:8080/api/cakes/1


### get cakes by category
GET localhost:8080/api/cakes/category/MOUSSE
